### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by lucbouge** [defjaf/pip_upgrade_outdated#1] opened 2018-04-22 17:12 UTC
Hello from France, Andrew,

I was looking for some easy way to update my outdated Python packages, and I spotted your script. It looks like exactly what I need, thanks.

However, I got a strange behavior on MacOS High Sierra 10.13.4.

Note that no package was outdated at that time. (I checked.)

Regards,

Luc.

```
bouge$ pip_upgrade_outdated --version
pip_upgrade_outdated 1.0

bouge$ pip --version
pip 10.0.1 from /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip (python 3.5)

bouge$ python --version
Python 3.5.5

bouge$ pip_upgrade_outdated 
Traceback (most recent call last):
  File "/Users/bouge/share/usr/bin/pip_upgrade_outdated", line 11, in <module>
    sys.exit(main())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip_upgrade_outdated/upgrade_pip_packages.py", line 120, in main
    packages = collect_packages(pip_cmd=pip_cmd, verbose=args.verbose)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip_upgrade_outdated/upgrade_pip_packages.py", line 80, in collect_packages
    pkgs = json.loads(stdout)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

```

**Comment by defjaf** [comment] 2018-04-23 09:12
Hi Luc,

This is weird -- I can't reproduce this. How did you install your python? (It looks like something like `fink` which I'm not that familiar with. I usually just use the direct python.org download, or sometimes homebrew) You have a slightly outdated version -- the current is 3.6 -- and it's also slightly weird that the `python` command defaults to `python3`, rather than the usual `python2`. 

However, I've tried installing python3.5 myself, and I don't see these errors...

Is it possible that you've got a different pip installed somewhere else? If so, you could try

    pip_upgrade_outdated -pip_cmd /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pip

Yours,

Andrew

**Comment by defjaf** [comment] 2018-04-23 09:33
Hi again, Luc, 

Ok, I'm still slightly confused, but I may have found a simple fix. If you want to try this beta version, I would appreciate it:

    pip install --upgrade git+ssh://git@github.com/defjaf/pip_upgrade_outdated.git

Alternately, if you are comfortable with editing source code directly, it's just a matter of changing

    pkgs = json.loads(stdout)

to

    pkgs = json.loads(stdout.decode())

in line 80 of the main `pip_upgrade_outdated/upgrade_pip_packages.py` file.

**Comment by defjaf** [comment] 2018-04-26 09:03
I think this is the fix... Closing (and uploading a new version to pypi)

**Closed as completed by defjaf** 2018-04-26 09:03 UTC

**Comment by lucbouge** [comment] 2018-04-26 10:23
Sorry for not reacting as fast as requested. Thanks for your commitment. I updated through pip. (NB: I am not sure about the meaning of the warning about `pyexcel-io 0.5.6`.)

 ```
bouge$ sudo -H pip install -U pip_upgrade_outdated
Collecting pip_upgrade_outdated
  Downloading https://files.pythonhosted.org/packages/44/1f/24b1213a47feb9761ae149687e046119d66bf87e9712507230ca7502e3d2/pip_upgrade_outdated-1.1-py2.py3-none-any.whl
Requirement not upgraded as not directly required: pip in /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages (from pip_upgrade_outdated) (10.0.1)
pyexcel-io 0.5.6 has requirement lml==0.0.1, but you'll have lml 0.0.2 which is incompatible.
Installing collected packages: pip-upgrade-outdated
  Found existing installation: pip-upgrade-outdated 1.0
    Uninstalling pip-upgrade-outdated-1.0:
      Successfully uninstalled pip-upgrade-outdated-1.0
  The script pip_upgrade_outdated is installed in '/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-upgrade-outdated-1.1
```
It looks to work, and I will be careful to spot the next outdated package. 

```
bouge$ /opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/pip_upgrade_outdated --version
pip_upgrade_outdated 1.1
bouge$ /opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/pip_upgrade_outdated -vvv
Namespace(dry_run=False, pip_cmd='pip', serial=True, verbose=3)
pip_cmd=pip
No outdated packages.
```

Regards,

Luc.

**Comment by defjaf** [comment] 2018-04-26 12:55
Hi Luc,

Great -- this seems like it is more or less working. 

The warning has to do with the default pip 10 [upgrade strategy](https://pip.pypa.io/en/stable/user_guide/#id23) and related warning messages, which tell you that `pyexcel-io` wants an outdated version of `lml`. 

If this actually matters, you shouldn't use my script, since it will just update everything that is outdated. However, I will think about different `upgrade-strategy` flags and/or an easy way to ignore certain packages. But I may not get to this soon or ever...

Keep me posted if there are any other issues.

**Comment by lucbouge** [comment] 2018-04-26 13:26
Thanks. I uninstalled pyexcel-io as I do not need it any longer. 
However, some alternative upgrade strategies will be of interest. 
Congrats for you contribution, Luc.
